image: golang:1.5
git:
  path: github.com/vjscjp/tempgo
script:
  - echo "build commands"
  - echo "no build command"
  - echo "no test command"
clone:
  path: github.com/vjscjp/tempgo
build:
  image: golang:1.5
  commands:
    - echo "build commands"
    - echo "no build command"
    - echo "no test command"
publish:
  docker:
    file: ./Dockerfile
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    


notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "http://shipped-api.tx3.shipped-cisco.com/webhooks/drone"
    on_success: true
    on_failure: true
